import Head from "next/head";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";

export default function CarVw(props) {
  const images = [
    "https://mobistatic3.focus.bg/mobile/photosmob/227/1/big1/11685691766485227_Fs.jpg",
    "https://mobistatic3.focus.bg/mobile/photosmob/227/1/big1/11685691766485227_jL.jpg",
    "https://mobistatic3.focus.bg/mobile/photosmob/227/1/big1/11685691766485227_Pq.jpg",
    "https://mobistatic3.focus.bg/mobile/photosmob/227/1/big1/11685691766485227_YW.jpg",
  ];
  const data = {
    title: "BMW i3 S 120 Ah",
    price: "55 999лв",
    date: "юни 2019г",
    engine: "Електрически",
    horsepower: "184кс",
    trans: "Автоматична",
    eco: "Евро 6",
    battery: "42.2 kWh",
    millage: "41 700км",
    color: "Бял",
    moreInfo: `20" Алуминиеви джанти тип Double Spoke 431 Apple carplay Мултифункционален волан, Контрол на налягането в гумите,     Система за комфортен достъп     Камера за обратно виждане     Електрически шибедах     Затъмнени задни стъкла
    Автоматично затъмняване на всички огледала
     Поставка за чаши отпред
     Подлатъкник отпред
     Пакет за съхранение
     Отопление на предните седалки
     Термопомпа
     Система за бързо зареждане с DC (прав ток)
     Система за зареждане АС Professional
     Акустична защита за пешеходци
     Парктроник отпред и отзад
     Сензор за дъжд
     Автоматичен двузонов климатик
     Адаптивни LED фарове
     Подсилено захранване
 Асистент за дълги светлини
     Асистент за задръстване
     Асистент за шофиране Plus с вкл. Активен автопилот със Stop & Go функция
     Навигационна система Professional
     DAB тунер
     Harman/ Kardon озвучителна система
     Connected Drive Services
     Телефония с функция за безжично зареждане на смартфон
     WLAN Hotspot
     Дистроник
    Колата има гаранция до- 06. 2024
    Батерията има гаранция до- 06. 2027
    `,
  };
  return (
    <div>
      <Head>
        <title>Car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <a id="home" class='link' href="/">Home</a>
        <div class="container">
          <h3 class="title">{data.title}</h3>
          <div className="carousel-container">
            <Swiper
              modules={[Navigation, Pagination, Scrollbar, A11y]}
              className="external-buttons"
              spaceBetween={24}
              slidesPerView={1}
              navigation
              updateOnWindowResize
              observer
              observerParents
              initialSlide={1}
              loop
            >
              {images.map((image, index) => (
                <SwiperSlide key={index}>
                  <img alt="img" className="image" src={image} />
                </SwiperSlide>
              ))}
            </Swiper>
            <div class="desc">
              <div class="namePrice">
              <p id="name">{data.title}</p>
              <p id="price">{data.price}</p>
              </div>
              <ul class="specs">
                <li>
                  Дата на производство : <p id="year">{data.date}</p>
                </li>
                <li>
                  Тип двигател: <p id="engine">{data.engine}</p>
                </li>
                <li>
                  Мощност: <p id="horsepower">{data.horsepower}</p>
                </li>
                <li>
                  Капацитет на батерия: <p id="battery">{data.battery}</p>
                </li>
                <li>
                  Скоростна кути: <p id="trans">{data.trans}</p>
                </li>
                <li>
                  Пробег: <p id="millage">{data.millage}</p>
                </li>
                <li>
                  Цвят: <p id="color">{data.color}</p>
                </li>
              </ul>
              <div class="more-info">Допълнителна Информация:</div>
              <p class="the-info">{data.moreInfo}</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
