import Head from "next/head";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";

export default function CarVw(props) {
  const images = [
    "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_9l.jpg",
    "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_UI.jpg",
    "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_RS.jpg",
    "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_my.jpg",
    "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_Z.jpg",
  ];
  const data = {
    title: "BMW M4 *Head-up*Pano*Harman Kardon*",
    price: "89 200лв",
    date: "октомври 2016г",
    engine: "Бензинов",
    horsepower: "431кс",
    trans: "Автоматична",
    eco: "Евро 6",
    millage: "103 300 км",
    color: "Син",
    moreInfo: `ПРЕДЛАГАМЕ ВИ ЛИЗИНГ ДО 48 МЕСЕЦА С ПРЕФЕРЕНЦИАЛНИ УСЛОВИЯ И БЪРЗО ОДОБРЕНИЕ, БЕЗ ДОКАЗВАНЕ НА ДОХОДИТЕ!
    Специално оборудване:
    Head-Up дисплей
    Парктроник
    Круиз контрол
    Автоматична климатична инсталация
    Панорамен покрив
    Лумбална опора
    Сензор за дъжд
    Harman Kardon озвучителна система
    Адаптивни LED фарове
    Пакет осветление
    Навигационна система Professional
    Комфортна телефония
    Ел. регулируеми седалки с функция памет
    Отопляеми предни седалки
    Обявената цена е крайна ! ! !
    `,
  };
  return (
    <div>
      <Head>
        <title>Car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <a id="home" class='link' href="/">Home</a>
        <div class="container">
          <h3 class="title">{data.title}</h3>
          <div className="carousel-container">
            <Swiper
              modules={[Navigation, Pagination, Scrollbar, A11y]}
              className="external-buttons"
              spaceBetween={24}
              slidesPerView={1}
              navigation
              updateOnWindowResize
              observer
              observerParents
              initialSlide={1}
              loop
            >
              {images.map((image, index) => (
                <SwiperSlide key={index}>
                  <img
                    alt="img"
                    className="image"
                    src={image}
                  />
                </SwiperSlide>
              ))}
            </Swiper>
            <div class="desc">
              <p id="name">{data.title}</p>
              <p id="price">{data.price}</p>
              <ul class="specs">
                <li>
                  Дата на производство : <p id="year">{data.date}</p>
                </li>
                <li>
                  Тип двигател: <p id="engine">{data.engine}</p>
                </li>
                <li>
                  Мощност: <p id="horsepower">{data.horsepower}</p>
                </li>
                <li>
                  Евростандарт: <p id="eco">{data.eco}</p>
                </li>
                <li>
                  Скоростна кути: <p id="trans">{data.trans}</p>
                </li>
                <li>
                  Пробег: <p id="millage">{data.millage}</p>
                </li>
                <li>
                  Цвят: <p id="color">{data.color}</p>
                </li>
              </ul>
              <div class="more-info">Допълнителна Информация:</div>
              <p class="the-info">{data.moreInfo}</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
